### ISSUE TITLE
Please provide specific versions that work

### ISSUE THREAD

**Issue by romanws** [USCDataScience/Image-Similarity-Deep-Ranking#4]
I'm getting lib compatibility problems after following the setup steps from the readme.

Can you provide details on what python version was used and what lib versions were the latest one at the time this project was last updated (I see last lib update was ~2 years ago). Specifically tensorflow 1.x/2.x and keras are problematic.

For libs, it would be great if the full list is provided - `pip3 freeze` can help.

Thanks!

**Comment by Akash20x** [comment]
I tried to run files of the repository in a virtual environment and found these python libraries version works fine in the project.

certifi==2020.12.5
chardet==4.0.0
h5py==3.1.0
idna==2.10
Keras==2.4.3
numpy==1.20.0
Pillow==8.1.0
PyYAML==5.4.1
requests==2.25.1
scipy==1.6.0
six==1.15.0
torch==1.7.1
torchsummary==1.5.1
torchvision==0.2.2.post3
tqdm==4.56.0
typing-extensions==3.7.4.3
urllib3==1.26.3
tensorflow==2.4.1

**Comment by romanws** [comment]
Thanks @Akash20x .

I took your versions but unfortunately I'm still having errors.
But since those versions work for you I guess I should close this issue, it has to be something specific in my env.

For reference, this is what I get:

```
get_distance.py --model ./deepranking-v2-150000.h5 --image1 img1.jpg --image2 img2.jpg
2021-02-05 18:56:29.181546: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-05 18:56:29.181747: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "get_distance.py", line 93, in <module>
    model = deep_rank_model()
  File "get_distance.py", line 69, in deep_rank_model
    convnet_model = convnet_model_()
  File "get_distance.py", line 54, in convnet_model_
    x = Lambda(lambda  x_: K.l2_normalize(x,axis=1))(x)
  File "/Users/roman/.virtualenvs/img-sim-3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 952, in __call__
    input_list)
  File "/Users/roman/.virtualenvs/img-sim-3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/Users/roman/.virtualenvs/img-sim-3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/Users/roman/.virtualenvs/img-sim-3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 869, in _infer_output_signature
    keras_tensor.keras_tensor_from_tensor, outputs)
  File "/Users/roman/.virtualenvs/img-sim-3/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 659, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/Users/roman/.virtualenvs/img-sim-3/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 659, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/Users/roman/.virtualenvs/img-sim-3/lib/python3.7/site-packages/tensorflow/python/keras/engine/keras_tensor.py", line 606, in keras_tensor_from_tensor
    out = keras_tensor_cls.from_tensor(tensor)
  File "/Users/roman/.virtualenvs/img-sim-3/lib/python3.7/site-packages/tensorflow/python/keras/engine/keras_tensor.py", line 205, in from_tensor
    type_spec = type_spec_module.type_spec_from_value(tensor)
  File "/Users/roman/.virtualenvs/img-sim-3/lib/python3.7/site-packages/tensorflow/python/framework/type_spec.py", line 554, in type_spec_from_value
    (value, type(value).__name__))
TypeError: Could not build a TypeSpec for <KerasTensor: shape=(None, 4096) dtype=float32 (created by layer 'tf.math.l2_normalize')> with type KerasTensor
```

**Comment by rokopi-byte** [comment]
@romanws how did you solve it? I have exactly the same issue, I just created an isolated environment as @Akash20x suggested, with the same packages version, without any luck..

**Comment by romanws** [comment]
@roccopietrini I'm sorry, I can't help. I'm no longer working on that project and of course I don't remember the resolution 😬

**Comment by rokopi-byte** [comment]
For anyone having the same issue, I think the code is just wrong.. in `get_distance.py` line 54:
`    x = Lambda(lambda  x_: K.l2_normalize(x,axis=1))(x)`
should be:
` x = Lambda(lambda  x_: K.l2_normalize(x_,axis=1))(x)`

With this fix it works with TF2.8 (just change the imports to be TF2 compatible)
